In [6]:
from multi_molecule import *
from multi_reaction import *
import ase
from ase import Atom, Atoms
from ase.calculators.gaussian import *
import numpy as np
from numpy import array, dtype
from rmgpy.qm.qmdata import *
import networkx as nx

In [2]:
f = open("../reference_files/[CH]=C(C)CCC=C(C)C=C+[H][H]_C=CC(C)=CCCC(=C)C+[H].ts", "r")
ts_lines = f.readlines()
f.close()
#ts_lines

In [3]:
rxn_label = ts_lines[0].split("\n")[0].split("""\"""")[1]
qm_data = ts_lines[-1].split(" = ")[-1].split("\n")[0]

In [4]:
try:
    qm_data = eval(qm_data)
except NameError:
    L, R = qm_data.split("int32")
    
    qm_data = L + """ "int32" """ + R
    qm_data = eval(qm_data)
    
qm_data

QMData(groundStateDegeneracy=2, numberOfAtoms=27, stericEnergy=None, molecularMass=(137.133,'amu'), energy=(-10641,'eV/molecule'), atomicNumbers=array([1, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32), rotationalConstants=([0.0861229,0.0186666,0.0177299],'cm^-1'), atomCoords=([[0.036757,0.0994,2.28903],[-0.672491,-0.1839,1.89657],[-1.94741,0.836597,-0.661486],[-0.528553,1.31777,-0.380271],[-3.77379,-0.871983,-0.258424],[2.31384,1.18079,0.79787],[1.73807,0.179518,-0.161023],[-2.47073,-0.27116,0.219776],[0.498832,0.257211,-0.656465],[2.59264,-0.941918,-0.562896],[3.83989,-1.1519,-0.149586],[-1.90379,-0.710139,1.32388],[-2.64592,1.67565,-0.587345],[-2.01239,0.495132,-1.70039],[-0.331843,2.18615,-1.01703],[-0.457259,1.67266,0.648368],[-4.15511,-1.61821,0.434547],[-4.52653,-0.089824,-0.378306],[-3.63494,-1.34007,-1.23508],[1.61265,1.9779,1.02783],[2.59926,0.694192,1.73316],[3.21648,1.63157,0.380446],[0.186864,-0.523771,-1.34622],[2.14287,-1.6475

In [5]:
atoms = qm_data.atomicNumbers
positions = qm_data.atomCoords.value
#print atoms, positions
print positions

[[ 0.036757  0.0994    2.28903 ]
 [-0.672491 -0.1839    1.89657 ]
 [-1.94741   0.836597 -0.661486]
 [-0.528553  1.31777  -0.380271]
 [-3.77379  -0.871983 -0.258424]
 [ 2.31384   1.18079   0.79787 ]
 [ 1.73807   0.179518 -0.161023]
 [-2.47073  -0.27116   0.219776]
 [ 0.498832  0.257211 -0.656465]
 [ 2.59264  -0.941918 -0.562896]
 [ 3.83989  -1.1519   -0.149586]
 [-1.90379  -0.710139  1.32388 ]
 [-2.64592   1.67565  -0.587345]
 [-2.01239   0.495132 -1.70039 ]
 [-0.331843  2.18615  -1.01703 ]
 [-0.457259  1.67266   0.648368]
 [-4.15511  -1.61821   0.434547]
 [-4.52653  -0.089824 -0.378306]
 [-3.63494  -1.34007  -1.23508 ]
 [ 1.61265   1.9779    1.02783 ]
 [ 2.59926   0.694192  1.73316 ]
 [ 3.21648   1.63157   0.380446]
 [ 0.186864 -0.523771 -1.34622 ]
 [ 2.14287  -1.64754  -1.25451 ]
 [ 4.40322  -2.009    -0.490342]
 [ 4.33688  -0.482043  0.539635]
 [-2.2526   -1.48702   1.99141 ]]


In [8]:
list_of_atoms = []
for i, pos in enumerate(positions):
    a = atoms[i]
    list_of_atoms.append(Atom(symbol=a, position=tuple(pos)))
    
mol = Atoms(list_of_atoms)

In [9]:
distance_matrix  = mol.get_all_distances()

In [10]:
graph = nx.from_numpy_matrix(distance_matrix,parallel_edges=True)

In [11]:
nx.write_gexf(graph,'test.gexf')

In [12]:
%%bash
cat test.gexf

<?xml version='1.0' encoding='utf-8'?>
<gexf version="1.2" xmlns="http://www.gexf.net/1.2draft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance">
  <graph defaultedgetype="undirected" mode="static" name="">
    <meta>
      <creator>NetworkX 2.1</creator>
      <lastmodified>25/01/2018</lastmodified>
    </meta>
    <nodes>
      <node id="0" label="0" />
      <node id="1" label="1" />
      <node id="2" label="2" />
      <node id="3" label="3" />
      <node id="4" label="4" />
      <node id="5" label="5" />
      <node id="6" label="6" />
      <node id="7" label="7" />
      <node id="8" label="8" />
      <node id="9" label="9" />
      <node id="10" label="10" />
      <node id="11" label="11" />
      <node id="12" label="12" />
      <node id="13" label="13" />
      <node id="14" label="14" />
      <node id="15" label="15" />
      <node id="16" label="16" />
      <node id="17" label="17" />
      <node id

In [9]:
rxn_label

'[CH]=C(C)CCC=C(C)C=C+[H][H]_C=CC(C)=CCCC(=C)C+[H]'

In [10]:
rxn = Multi_Reaction(label=rxn_label, reaction_family="H_Abstraction")

reaction.py:300 generateBoundsMatrix INFO Generating bounds matrix for [CH]=C(C)CCC=C(C)C=C.[H][H]
reaction.py:338 bmPreEdit INFO Changing lower limit 2.275316 to 2.205539
reaction.py:338 bmPreEdit INFO Changing lower limit 3.15 to 2.64649597268


In [11]:
rxn.multi_ts.rmg_ts

OSError: cannot load library libcairo.so.2: libXrender.so.1: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.so.2'

Molecule(SMILES="[CH]=C(C)CCC=C(C)C=C.[H][H]")

In [12]:
if getDB("forbidden") is not None:
    print "w"

NameError: name 'getDB' is not defined

In [ ]:
type(getDB("forbidden"))

In [ ]:
str(type(getDB("forbidden")))

In [ ]:
print None

In [ ]:
qm_data.

In [ ]:
mol = Molecule()
mol

In [ ]:
print mol.fromXYZ(atoms, positions)

In [ ]:
from rmgpy.molecule.molecule import Atom as  rmg_atom
#from rmgpy.molecule.element import Element as Element
import element as elements
for number, position in zip(atoms, positions):
    _rdkit_periodic_table = elements.GetPeriodicTable()
    atom = Atom(_rdkit_periodic_table.GetElementSymbol(int(number)))
    atom.coords = position

In [ ]:
Atom?