In [1]:
from multi_molecule import *
from multi_reaction import *
import ase
from ase import Atom, Atoms
from ase.calculators.gaussian import *
import numpy as np
from numpy import array, dtype


thermo.py:789 loadLibraries INFO Loading thermodynamics library from primaryThermoLibrary.py in /Users/nathan/Code/RMG-database/input/thermo/libraries...
thermo.py:789 loadLibraries INFO Loading thermodynamics library from KlippensteinH2O2.py in /Users/nathan/Code/RMG-database/input/thermo/libraries...
thermo.py:789 loadLibraries INFO Loading thermodynamics library from thermo_DFT_CCSDTF12_BAC.py in /Users/nathan/Code/RMG-database/input/thermo/libraries...
thermo.py:789 loadLibraries INFO Loading thermodynamics library from CBS_QB3_1dHR.py in /Users/nathan/Code/RMG-database/input/thermo/libraries...
thermo.py:806 loadGroups INFO Loading thermodynamics group database from /Users/nathan/Code/RMG-database/input/thermo/groups...
transport.py:294 loadGroups INFO Loading transport group database from /Users/nathan/Code/RMG-database/input/transport/groups...
database.py:165 loadFamilies INFO Loading the user-specified kinetics families from /Users/nathan/Code/RMG-database/input/kinetics/famil

In [2]:
f = open("../[CH]=C(C)CCC=C(C)C=C+[H][H]_C=CC(C)=CCCC(=C)C+[H].ts", "r")
ts_lines = f.readlines()
f.close()
ts_lines

['rxnLabel = "[CH]=C(C)CCC=C(C)C=C+[H][H]_C=CC(C)=CCCC(=C)C+[H]"\n',
 'method = "m062x"\n',
 "qmData = QMData(groundStateDegeneracy=2, numberOfAtoms=27, stericEnergy=None, molecularMass=(137.133,'amu'), energy=(-10641,'eV/molecule'), atomicNumbers=array([1, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32), rotationalConstants=([0.0861229,0.0186666,0.0177299],'cm^-1'), atomCoords=([[0.036757,0.0994,2.28903],[-0.672491,-0.1839,1.89657],[-1.94741,0.836597,-0.661486],[-0.528553,1.31777,-0.380271],[-3.77379,-0.871983,-0.258424],[2.31384,1.18079,0.79787],[1.73807,0.179518,-0.161023],[-2.47073,-0.27116,0.219776],[0.498832,0.257211,-0.656465],[2.59264,-0.941918,-0.562896],[3.83989,-1.1519,-0.149586],[-1.90379,-0.710139,1.32388],[-2.64592,1.67565,-0.587345],[-2.01239,0.495132,-1.70039],[-0.331843,2.18615,-1.01703],[-0.457259,1.67266,0.648368],[-4.15511,-1.61821,0.434547],[-4.52653,-0.089824,-0.378306],[-3.63494,-1.34007,-1.23508],[1.61265,1.9779,1.0278

In [3]:
from rmgpy.qm.qmdata import *
ts_lines[-1]

"qmData = QMData(groundStateDegeneracy=2, numberOfAtoms=27, stericEnergy=None, molecularMass=(137.133,'amu'), energy=(-10641,'eV/molecule'), atomicNumbers=array([1, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32), rotationalConstants=([0.0861229,0.0186666,0.0177299],'cm^-1'), atomCoords=([[0.036757,0.0994,2.28903],[-0.672491,-0.1839,1.89657],[-1.94741,0.836597,-0.661486],[-0.528553,1.31777,-0.380271],[-3.77379,-0.871983,-0.258424],[2.31384,1.18079,0.79787],[1.73807,0.179518,-0.161023],[-2.47073,-0.27116,0.219776],[0.498832,0.257211,-0.656465],[2.59264,-0.941918,-0.562896],[3.83989,-1.1519,-0.149586],[-1.90379,-0.710139,1.32388],[-2.64592,1.67565,-0.587345],[-2.01239,0.495132,-1.70039],[-0.331843,2.18615,-1.01703],[-0.457259,1.67266,0.648368],[-4.15511,-1.61821,0.434547],[-4.52653,-0.089824,-0.378306],[-3.63494,-1.34007,-1.23508],[1.61265,1.9779,1.02783],[2.59926,0.694192,1.73316],[3.21648,1.63157,0.380446],[0.186864,-0.523771,-1.34622],[2.142

In [4]:
rxn_label = ts_lines[0].split("\n")[0].split("""\"""")[1]
qm_data = ts_lines[-1].split(" = ")[-1].split("\n")[0]


In [5]:
try:
    qm_data = eval(qm_data)
except NameError:
    L, R = qm_data.split("int32")
    
    qm_data = L + """ "int32" """ + R
    print qm_data
    qm_data = eval(qm_data)
    
qm_data

QMData(groundStateDegeneracy=2, numberOfAtoms=27, stericEnergy=None, molecularMass=(137.133,'amu'), energy=(-10641,'eV/molecule'), atomicNumbers=array([1, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype= "int32" ), rotationalConstants=([0.0861229,0.0186666,0.0177299],'cm^-1'), atomCoords=([[0.036757,0.0994,2.28903],[-0.672491,-0.1839,1.89657],[-1.94741,0.836597,-0.661486],[-0.528553,1.31777,-0.380271],[-3.77379,-0.871983,-0.258424],[2.31384,1.18079,0.79787],[1.73807,0.179518,-0.161023],[-2.47073,-0.27116,0.219776],[0.498832,0.257211,-0.656465],[2.59264,-0.941918,-0.562896],[3.83989,-1.1519,-0.149586],[-1.90379,-0.710139,1.32388],[-2.64592,1.67565,-0.587345],[-2.01239,0.495132,-1.70039],[-0.331843,2.18615,-1.01703],[-0.457259,1.67266,0.648368],[-4.15511,-1.61821,0.434547],[-4.52653,-0.089824,-0.378306],[-3.63494,-1.34007,-1.23508],[1.61265,1.9779,1.02783],[2.59926,0.694192,1.73316],[3.21648,1.63157,0.380446],[0.186864,-0.523771,-1.34622],[2.14287,-1.

QMData(groundStateDegeneracy=2, numberOfAtoms=27, stericEnergy=None, molecularMass=(137.133,'amu'), energy=(-10641,'eV/molecule'), atomicNumbers=array([1, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32), rotationalConstants=([0.0861229,0.0186666,0.0177299],'cm^-1'), atomCoords=([[0.036757,0.0994,2.28903],[-0.672491,-0.1839,1.89657],[-1.94741,0.836597,-0.661486],[-0.528553,1.31777,-0.380271],[-3.77379,-0.871983,-0.258424],[2.31384,1.18079,0.79787],[1.73807,0.179518,-0.161023],[-2.47073,-0.27116,0.219776],[0.498832,0.257211,-0.656465],[2.59264,-0.941918,-0.562896],[3.83989,-1.1519,-0.149586],[-1.90379,-0.710139,1.32388],[-2.64592,1.67565,-0.587345],[-2.01239,0.495132,-1.70039],[-0.331843,2.18615,-1.01703],[-0.457259,1.67266,0.648368],[-4.15511,-1.61821,0.434547],[-4.52653,-0.089824,-0.378306],[-3.63494,-1.34007,-1.23508],[1.61265,1.9779,1.02783],[2.59926,0.694192,1.73316],[3.21648,1.63157,0.380446],[0.186864,-0.523771,-1.34622],[2.14287,-1.6475

In [6]:
atoms = qm_data.atomicNumbers
positions = qm_data.atomCoords.value
print atoms, positions

[1 1 6 6 6 6 6 6 6 6 6 6 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] [[ 0.036757  0.0994    2.28903 ]
 [-0.672491 -0.1839    1.89657 ]
 [-1.94741   0.836597 -0.661486]
 [-0.528553  1.31777  -0.380271]
 [-3.77379  -0.871983 -0.258424]
 [ 2.31384   1.18079   0.79787 ]
 [ 1.73807   0.179518 -0.161023]
 [-2.47073  -0.27116   0.219776]
 [ 0.498832  0.257211 -0.656465]
 [ 2.59264  -0.941918 -0.562896]
 [ 3.83989  -1.1519   -0.149586]
 [-1.90379  -0.710139  1.32388 ]
 [-2.64592   1.67565  -0.587345]
 [-2.01239   0.495132 -1.70039 ]
 [-0.331843  2.18615  -1.01703 ]
 [-0.457259  1.67266   0.648368]
 [-4.15511  -1.61821   0.434547]
 [-4.52653  -0.089824 -0.378306]
 [-3.63494  -1.34007  -1.23508 ]
 [ 1.61265   1.9779    1.02783 ]
 [ 2.59926   0.694192  1.73316 ]
 [ 3.21648   1.63157   0.380446]
 [ 0.186864 -0.523771 -1.34622 ]
 [ 2.14287  -1.64754  -1.25451 ]
 [ 4.40322  -2.009    -0.490342]
 [ 4.33688  -0.482043  0.539635]
 [-2.2526   -1.48702   1.99141 ]]


In [7]:
rxn_label

'[CH]=C(C)CCC=C(C)C=C+[H][H]_C=CC(C)=CCCC(=C)C+[H]'

In [10]:
rxn = Multi_Reaction(label=rxn_label, reaction_family="H_Abstraction")

reaction.py:300 generateBoundsMatrix INFO Generating bounds matrix for [CH]=C(C)CCC=C(C)C=C.[H][H]


<rmgpy.data.base.ForbiddenStructures instance at 0x1108c4c20>
<rmgpy.data.base.ForbiddenStructures instance at 0x1108c4c20>
<rmgpy.data.base.ForbiddenStructures instance at 0x1108c4c20>
<rmgpy.data.base.ForbiddenStructures instance at 0x1108c4c20>
<rmgpy.data.base.ForbiddenStructures instance at 0x1108c4c20>
<rmgpy.data.base.ForbiddenStructures instance at 0x1108c4c20>
<rmgpy.data.base.ForbiddenStructures instance at 0x1108c4c20>
<rmgpy.data.base.ForbiddenStructures instance at 0x1108c4c20>


reaction.py:338 bmPreEdit INFO Changing lower limit 2.275316 to 2.205539
reaction.py:338 bmPreEdit INFO Changing lower limit 3.15 to 2.64649597268
molecule.py:167 rd_embed INFO RDKit failed to embed on attempt 1 of 1000


In [20]:
rxn.multi_ts.rmg_ts

array([-2.72451288,  2.47709127, -0.95356769])

In [ ]:
if getDB("forbidden") is not None:
    print "w"

In [ ]:
type(getDB("forbidden"))

In [ ]:
str(type(getDB("forbidden")))

In [ ]:
print None

In [21]:
qm_data.

QMData(groundStateDegeneracy=2, numberOfAtoms=27, stericEnergy=None, molecularMass=(137.133,'amu'), energy=(-10641,'eV/molecule'), atomicNumbers=array([1, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32), rotationalConstants=([0.0861229,0.0186666,0.0177299],'cm^-1'), atomCoords=([[0.036757,0.0994,2.28903],[-0.672491,-0.1839,1.89657],[-1.94741,0.836597,-0.661486],[-0.528553,1.31777,-0.380271],[-3.77379,-0.871983,-0.258424],[2.31384,1.18079,0.79787],[1.73807,0.179518,-0.161023],[-2.47073,-0.27116,0.219776],[0.498832,0.257211,-0.656465],[2.59264,-0.941918,-0.562896],[3.83989,-1.1519,-0.149586],[-1.90379,-0.710139,1.32388],[-2.64592,1.67565,-0.587345],[-2.01239,0.495132,-1.70039],[-0.331843,2.18615,-1.01703],[-0.457259,1.67266,0.648368],[-4.15511,-1.61821,0.434547],[-4.52653,-0.089824,-0.378306],[-3.63494,-1.34007,-1.23508],[1.61265,1.9779,1.02783],[2.59926,0.694192,1.73316],[3.21648,1.63157,0.380446],[0.186864,-0.523771,-1.34622],[2.14287,-1.6475

In [32]:
mol = Molecule()
mol

draw.py:198 draw ERROR Error while drawing molecule : zero-size array to reduction operation maximum which has no identity
Traceback (most recent call last):
  File "/Users/nathan/Code/RMG-discovery/rmgpy/molecule/draw.py", line 191, in draw
    self.__generateCoordinates()
  File "/Users/nathan/Code/RMG-discovery/rmgpy/molecule/draw.py", line 397, in __generateCoordinates
    ranges = numpy.ptp(coordinates, axis = 0)
  File "/Users/nathan/anaconda/envs/rmg_env/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2197, in ptp
    return ptp(axis, out)
ValueError: zero-size array to reduction operation maximum which has no identity


IOError: [Errno 2] No such file or directory: 'temp_molecule.png'

Molecule(SMILES="", multiplicity=-187)

In [34]:
print mol.fromXYZ(atoms, positions)

TypeError: Cannot convert rmgpy.molecule.molecule.Atom to rmgpy.molecule.molecule.Bond

In [43]:
from rmgpy.molecule.molecule import Atom as  rmg_atom
#from rmgpy.molecule.element import Element as Element
import element as elements
for number, position in zip(atoms, positions):
    _rdkit_periodic_table = elements.GetPeriodicTable()
    atom = Atom(_rdkit_periodic_table.GetElementSymbol(int(number)))
    atom.coords = position

ImportError: No module named element

In [37]:
Atom?